### ISSUE TITLE
Why the error message ?

### ISSUE THREAD

**Issue by jhaiWang** [embracesource-cv-com/keras-east#2]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by yizt** [comment]
@jhaiWang 您好，不清楚您遇到的错误；能否详细描述一下？谢谢！

**Comment by jhaiWang** [comment]
大概是因为内存的原因，我把config里面的IMAGE_PER_GPU=2修改成16，就会出现上面的错误，把这个值调低一点就可以
------------------ 原始邮件 ------------------
发件人: "mick.yi"<notifications@github.com>;
发送时间: 2019年4月23日(星期二) 中午1:57
收件人: "embracesource-cv-com/keras-east"<keras-east@noreply.github.com>;
抄送: "北纬51°~~华丽的伪装"<240349215@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [embracesource-cv-com/keras-east] Why the error message ? (#2)




@jhaiWang 您好，不清楚您遇到的错误；能否详细描述一下？谢谢！

**Comment by bharatsubedi** [comment]
![image](https://user-images.githubusercontent.com/14069935/56810371-200fa480-6871-11e9-9390-ebb739e31797.png)
after run evaluate.py I faced this issue. can you tell me how to solve?

**Comment by yizt** [comment]
@bharatsubedi 感谢您的反馈，这是bug,已经修复

**Comment by jhaiWang** [comment]
您好：
     我想问一下您这个实验跑数据的时候，用的是什么数据库，跑了多久呢？我的5000张图片，跑一次Epoch就要一天的时间了，这个有点太慢了


------------------ 原始邮件 ------------------
发件人: "mick.yi"<notifications@github.com>;
发送时间: 2019年4月23日(星期二) 中午1:57
收件人: "embracesource-cv-com/keras-east"<keras-east@noreply.github.com>;
抄送: "北纬51°~~华丽的伪装"<240349215@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [embracesource-cv-com/keras-east] Why the error message ? (#2)




@jhaiWang 您好，不清楚您遇到的错误；能否详细描述一下？谢谢！

**Comment by yizt** [comment]
@jhaiWang ICDAR2015 训练集，1000张图像，1个epochs 平均155秒

**Comment by jhaiWang** [comment]
那这个差距还有点大啊，我现在自己的数据集，5000张图片，而且只标注了一个位置，GPU是1070ti，现在跑一个epoch要几个小时，这差距有点大，1000张数据是不是有点少？




------------------ 原始邮件 ------------------
发件人: "mick.yi"<notifications@github.com>;
发送时间: 2019年4月28日(星期天) 上午9:34
收件人: "embracesource-cv-com/keras-east"<keras-east@noreply.github.com>;
抄送: "北纬51°~~华丽的伪装"<240349215@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [embracesource-cv-com/keras-east] Why the error message ? (#2)




@jhaiWang ICDAR2015 训练集，1000张图像，1个epochs 平均155秒

**Comment by WJinhai** [comment]
make: Entering directory '/media/image/新加卷/kaggle/keras-east-master/lanms'
g++ -o adaptor.so -I include  -std=c++11 -O3 -I/root/anaconda3/envs/keras/include/python3.6m -L/home/image/anaconda3/envs/tensorflow/lib/python3.5/config-3.5m -L/home/image/anaconda3/envs/tensorflow/lib -lpython3.5m -lpthread -ldl  -lutil -lrt -lm  -Xlinker -export-dynamic adaptor.cpp include/clipper/clipper.cpp --shared -fPIC
In file included from include/pybind11/pytypes.h:12:0,
                 from include/pybind11/cast.h:13,
                 from include/pybind11/attr.h:13,
                 from include/pybind11/pybind11.h:43,
                 from adaptor.cpp:1:
include/pybind11/common.h:100:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
make: *** [adaptor.so] Error 1
Traceback (most recent call last):
  File "/media/image/新加卷/kaggle/keras-east-master/evaluate.py", line 20, in <module>
    import lanms
  File "/media/image/新加卷/kaggle/keras-east-master/lanms/__init__.py", line 8, in <module>
    raise RuntimeError('Cannot compile lanms: {}'.format(BASE_DIR))
RuntimeError: Cannot compile lanms: /media/image/新加卷/kaggle/keras-east-master/lanms

用了最新的代码compile出现问题
